In [45]:
a={5,6,7},
a

({5, 6, 7},)

In [34]:
print("njjb")

njjb


In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [49]:
a = np.array([0,1,2,3,4,5,6,7,8]) #list of list
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [56]:
a.dtype.name


'int64'

In [43]:
np.pi

3.141592653589793

In [52]:
a+=2
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
a=a*a
a

array([     6561,     65536,    390625,   1679616,   5764801,  16777216,
        43046721, 100000000, 214358881])

In [68]:
aa=np.array([5,6,5,4,5,5,5,6,5,3,2,8])
aa.reshape(2,-1)
aa

array([5, 6, 5, 4, 5, 5, 5, 6, 5, 3, 2, 8])