### Importing libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## NumPy

NumPy is the fundamental package for scientific computing in Python
Lists grow dynamically. Numpy is fixed size
Lists can have multiple data types. Numpy fixed data type

In [3]:
x=

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [4]:
x = np.arange(9).reshape(3,3) 
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
x.shape

(3, 3)

In [6]:
x.ndim

2

In [7]:
x.dtype.name

'int32'

In [8]:
x.itemsize

4

In [3]:
x.size

NameError: name 'x' is not defined

In [10]:
type(a)

list

In [2]:
type(x)

NameError: name 'x' is not defined

In [1]:
np.array(1,2,3)

NameError: name 'np' is not defined

In [13]:
x = np.array([1,2,3])
y = np.array([1.1,2.2,3.3])

In [14]:
x.dtype

dtype('int32')

In [15]:
y.dtype

dtype('float64')

In [16]:
c  = np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [19]:
np.empty((3,2))

array([[9.76118064e-313, 2.46151512e-312],
       [2.31297541e-312, 2.22809558e-312],
       [2.14321575e-312, 0.00000000e+000]])

In [20]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [22]:
np.pi

3.141592653589793

In [23]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [24]:
np.sin(np.pi/2)

1.0

### Operations on numpy arrays

In [25]:
a = [1,2,3,4,5]
for i in range(len(a)):
    a[i]+=1
a

[2, 3, 4, 5, 6]

In [26]:
a = np.array([1,2,3,4,5])
a+=1
a

array([2, 3, 4, 5, 6])

In [27]:
a = [1,2,3]
b = [1,2,3]
c=[]
for i in range(3):
    c.append(a[i]+b[i])
c

[2, 4, 6]

In [28]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a+b
c

array([2, 4, 6])

In [29]:
a = np.array([1,2,3])

In [30]:
a + 1

array([2, 3, 4])

In [31]:
a ** 2

array([1, 4, 9], dtype=int32)

In [32]:
a - 1

array([0, 1, 2])

In [33]:
a * 3

array([3, 6, 9])

In [34]:
a > 3

array([False, False, False])

In [35]:
a == 3

array([False, False,  True])

In [36]:
a < 4

array([ True,  True,  True])

In [37]:
a < 3

array([ True,  True, False])

In [38]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

In [39]:
A+B

array([[2, 4],
       [6, 8]])

In [40]:
A-B

array([[0, 0],
       [0, 0]])

In [41]:
A*B

array([[ 1,  4],
       [ 9, 16]])

In [42]:
A/B

array([[1., 1.],
       [1., 1.]])

In [43]:
A.dot(B)

array([[ 7, 10],
       [15, 22]])

### Operation and assignment

In [44]:
X = np.array([1,2,3])
Y = np.array([1,2,3])

In [45]:
X+=3
X

array([4, 5, 6])

In [46]:
X-=3
X

array([1, 2, 3])

In [47]:
X=X**2
X

array([1, 4, 9], dtype=int32)

In [48]:
X+=Y
X

array([ 2,  6, 12], dtype=int32)

In [49]:
X = np.array([1,2,3])
Y = np.array([1.1,2.2,3.3])

In [50]:
X.dtype

dtype('int32')

In [51]:
Y.dtype

dtype('float64')

In [52]:
Z=X+Y

In [53]:
Z.dtype

dtype('float64')

In [54]:
Z = np.random.random((2,3))
Z

array([[0.78499345, 0.49612183, 0.46763024],
       [0.77072999, 0.1042317 , 0.14972479]])

In [55]:
Z.sum()

2.7734319933859197

In [56]:
Z.min()

0.10423169646712416

In [57]:
Z.max()

0.7849934483273542

In [58]:
Z.sum(axis=0) #sum of each column

array([1.55572343, 0.60035353, 0.61735503])

In [59]:
Z.min(axis=1) #min of each row

array([0.46763024, 0.1042317 ])

In [60]:
Z.cumsum(axis=1) #cummulative sum of each row

array([[0.78499345, 1.28111528, 1.74874552],
       [0.77072999, 0.87496168, 1.02468647]])

### Universal Operations

In [61]:
H = np.arange(5)
H

array([0, 1, 2, 3, 4])

In [62]:
np.exp(H)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [63]:
np.sqrt(H)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [64]:
I = np.ones(5)
I

array([1., 1., 1., 1., 1.])

In [65]:
np.add(H,I)

array([1., 2., 3., 4., 5.])

### Index and Slicing

In [66]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
A[2]

2

In [68]:
A[2:5]

array([2, 3, 4])

In [69]:
A[::2]

array([0, 2, 4, 6, 8])

In [70]:
B = np.arange(25).reshape(5,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [71]:
B[2,3]

13

In [72]:
B[:,0]

array([ 0,  5, 10, 15, 20])

In [73]:
B[0,:]

array([0, 1, 2, 3, 4])

In [74]:
B[1:3,0]

array([ 5, 10])

In [75]:
B[-1]

array([20, 21, 22, 23, 24])

In [76]:
B[-1,:]

array([20, 21, 22, 23, 24])

In [77]:
X = np.arange(36).reshape(6,6)
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
X.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [79]:
X.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [80]:
X.reshape(9,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [81]:
X.reshape(9,4).shape

(9, 4)

In [82]:
X.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [83]:
X.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [84]:
X.T.shape

(6, 6)

In [85]:
Y = np.arange(36).reshape(4,9)
Y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [86]:
Y.resize(6,6)
Y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [87]:
X = np.arange(12)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [88]:
np.hsplit(X,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [89]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
np.vsplit(X,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### Linear Algebra

In [91]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [92]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [93]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [94]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [95]:
np.trace(u)

2.0

In [96]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [97]:
j.dot(j)

array([[-1.,  0.],
       [ 0., -1.]])

In [98]:
y = np.array([[5.], [7.]])
y

array([[5.],
       [7.]])

In [99]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [100]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

## Pandas

Series:
A one-dimensional labeled array capable of holding any data type

In [102]:
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])

In [104]:
s

a    3
b   -5
c    7
d    4
dtype: int64

DataFrame:
A two-dimensional labeled data structure with columns of potentially different types

In [108]:
data = {'Country': ['Belgium',  'India',  'Brazil'],

'Capital': ['Brussels',  'New Delhi',  'Brasilia'],

'Population': [11190846, 1303171035, 207847528]}


In [109]:
 df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])

In [110]:
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

I/O:
Read and Write to CSV

In [111]:
# pd.read_csv('file.csv', header=None, nrows=5)
# pd.to_csv('myDataFrame.csv')

Read multiple sheets from the same file

In [112]:
# xlsx = pd.ExcelFile('file.xls')
# df = pd.read_excel(xlsx,  'Sheet1')

Read and Write to Excel

In [113]:
# pd.read_excel('file.xlsx')
# pd.to_excel('dir/myDataFrame.xlsx',  sheet_name='Sheet1')

## Selection


# Getting

Get one element:

In [114]:
s['b']

-5

Get subset of a DataFrame:

In [115]:
df[1:]

Country    Capital  Population
1   India  New Delhi  1303171035
2  Brazil   Brasilia   207847528

Select single value by row and and column:

In [139]:
df.iloc[0][0]

'Belgium'

In [143]:
df.iat[0,0]

'Belgium'

Select single value by row and column labels

In [145]:
df.loc[0:,['Country']]

Country
0  Belgium
1    India
2   Brazil