### Importing libraries

In [384]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## NumPy

NumPy is the fundamental package for scientific computing in Python
Lists grow dynamically. Numpy is fixed size
Lists can have multiple data types. Numpy fixed data type

In [225]:
a = [[0,1,2],[3,4,5],[6,7,8]] #list of list
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [228]:
x = np.arange(9).reshape(3,3) 
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [229]:
x.shape

(3, 3)

In [231]:
x.ndim

2

In [233]:
x.dtype.name

'int64'

In [234]:
x.itemsize

8

In [235]:
x.size

9

In [236]:
type(a)

list

In [237]:
type(x)

numpy.ndarray

In [242]:
np.array(1,2,3)

ValueError: only 2 non-keyword arguments accepted

In [238]:
x = np.array([1,2,3])
y = np.array([1.1,2.2,3.3])

In [240]:
x.dtype

dtype('int64')

In [241]:
y.dtype

dtype('float64')

In [244]:
c  = np.array([[1,2],[3,4]],dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [245]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [248]:
np.ones((2,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [249]:
np.empty((3,2))

array([[-1.49166815e-154,  1.73059401e-077],
       [ 2.13575690e-314,  2.29041111e-314],
       [ 0.00000000e+000,  4.17201348e-309]])

In [250]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [251]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [252]:
np.pi

3.141592653589793

In [253]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [258]:
np.sin(np.pi/2)

1.0

### Operations on numpy arrays

In [260]:
a = [1,2,3,4,5]
for i in range(len(a)):
    a[i]+=1
a

[2, 3, 4, 5, 6]

In [262]:
a = np.array([1,2,3,4,5])
a+=1
a

array([2, 3, 4, 5, 6])

In [263]:
a = [1,2,3]
b = [1,2,3]
c=[]
for i in range(3):
    c.append(a[i]+b[i])
c

[2, 4, 6]

In [264]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a+b
c

array([2, 4, 6])

In [271]:
a = np.array([1,2,3])

In [272]:
a + 1

array([2, 3, 4])

In [273]:
a ** 2

array([1, 4, 9])

In [274]:
a - 1

array([0, 1, 2])

In [275]:
a * 3

array([3, 6, 9])

In [276]:
a > 3

array([False, False, False])

In [277]:
a == 3

array([False, False,  True])

In [278]:
a < 4

array([ True,  True,  True])

In [279]:
a < 3

array([ True,  True, False])

In [281]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])

In [282]:
A+B

array([[2, 4],
       [6, 8]])

In [283]:
A-B

array([[0, 0],
       [0, 0]])

In [284]:
A*B

array([[ 1,  4],
       [ 9, 16]])

In [285]:
A/B

array([[1, 1],
       [1, 1]])

In [286]:
A.dot(B)

array([[ 7, 10],
       [15, 22]])

### Operation and assignment

In [301]:
X = np.array([1,2,3])
Y = np.array([1,2,3])

In [302]:
X+=3
X

array([4, 5, 6])

In [303]:
X-=3
X

array([1, 2, 3])

In [304]:
X=X**2
X

array([1, 4, 9])

In [306]:
X+=Y
X

array([ 3,  8, 15])

In [308]:
X = np.array([1,2,3])
Y = np.array([1.1,2.2,3.3])

In [309]:
X.dtype

dtype('int64')

In [310]:
Y.dtype

dtype('float64')

In [311]:
Z=X+Y

In [312]:
Z.dtype

dtype('float64')

In [316]:
Z = np.random.random((2,3))
Z

array([[0.86051096, 0.0101283 , 0.51241396],
       [0.1755392 , 0.12205526, 0.41065343]])

In [317]:
Z.sum()

2.091301110757175

In [318]:
Z.min()

0.010128299593073486

In [319]:
Z.max()

0.8605109579976287

In [320]:
Z.sum(axis=0) #sum of each column

array([1.03605015, 0.13218356, 0.9230674 ])

In [321]:
Z.min(axis=1) #min of each row

array([0.0101283 , 0.12205526])

In [322]:
Z.cumsum(axis=1) #cummulative sum of each row

array([[0.86051096, 0.87063926, 1.38305322],
       [0.1755392 , 0.29759446, 0.70824789]])

### Universal Operations

In [325]:
H = np.arange(5)
H

array([0, 1, 2, 3, 4])

In [326]:
np.exp(H)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [327]:
np.sqrt(H)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [329]:
I = np.ones(5)
I

array([1., 1., 1., 1., 1.])

In [330]:
np.add(H,I)

array([1., 2., 3., 4., 5.])

### Index and Slicing

In [335]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [336]:
A[2]

2

In [337]:
A[2:5]

array([2, 3, 4])

In [338]:
A[::2]

array([0, 2, 4, 6, 8])

In [339]:
B = np.arange(25).reshape(5,5)
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [340]:
B[2,3]

13

In [344]:
B[:,0]

array([ 0,  5, 10, 15, 20])

In [343]:
B[0,:]

array([0, 1, 2, 3, 4])

In [345]:
B[1:3,0]

array([ 5, 10])

In [346]:
B[-1]

array([20, 21, 22, 23, 24])

In [347]:
B[-1,:]

array([20, 21, 22, 23, 24])

In [352]:
X = np.arange(36).reshape(6,6)
X

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [353]:
X.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [354]:
X.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [355]:
X.reshape(9,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [361]:
X.reshape(9,4).shape

(9, 4)

In [365]:
X.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [357]:
X.T

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

In [358]:
X.T.shape

(6, 6)

In [363]:
Y = np.arange(36).reshape(4,9)
Y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [364]:
Y.resize(6,6)
Y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [367]:
X = np.arange(12)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [368]:
np.hsplit(X,3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

In [370]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [372]:
np.vsplit(X,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### Linear Algebra

In [373]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
a

array([[1., 2.],
       [3., 4.]])

In [374]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [375]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [377]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [379]:
np.trace(u)

2.0

In [378]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])
j

array([[ 0., -1.],
       [ 1.,  0.]])

In [380]:
j.dot(j)

array([[-1.,  0.],
       [ 0., -1.]])

In [381]:
y = np.array([[5.], [7.]])
y

array([[5.],
       [7.]])

In [382]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [383]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

## Pandas